### ISSUE TITLE
flutter\ephemeral\Generated.props没有给

### ISSUE THREAD

**Issue by eiyooooo** [Sunbreak/Plugin-Flutter-Win32#4]
flutter\ephemeral\Generated.props没有给
打不开project

**Comment by Sunbreak** [comment]
1. 配置Flutter环境：https://flutter.dev/docs/get-started/install
2. 配置Flutter分支，即cmd中执行`flutter channel master`
3. 配置Flutter for Windows编译，即cmd中执行`flutter config --enable-windows-desktop`
4. 确保编译所需环境，即cmd中执行`flutter doctor -v`，检查Windows编译所需编译链
5. 拉取依赖库，即cmd中进入项目example路径，执行`flutter packages get`
6. Debug运行项目，即cmd中进入项目example路径，执行`flutter run`
